#Continiues Docker image deploiment of APERIMs EpitopeSelector
sudo: required

services:
  - docker

language: python

before_install:
  - docker build -t aperim/epitopeselector docker/
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push aperim/epitopeselector;

