#Continiues Docker image deploiment of APERIMs EpitopeSelector
sudo: required

services:
  - docker

install:
  - docker build -t aperim/epitopeselector docker/
  
script:
 docker run aperim/epitopeselector -h
